spring.application.name=SafetyNetAlerts

logging.level.root=ERROR
logging.level.com.openclassrooms=INFO
logging.file.name=logs/safetynetalerts.log

data.path=./data/datas.json
data.classpath-seed=datas.json